// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScorpionBusterBackEnd.Models
{
    public partial class AddToInventoryResult
    {
    }
}
