// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScorpionBusterBackEnd.Models
{
    public partial class GetUnequipedEquipmentResult
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool equiped { get; set; }
        public string type { get; set; }
        public int stat_value { get; set; }
        public bool owned { get; set; }
    }
}
