// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScorpionBusterBackEnd.Models
{
    public partial class Indice
    {
        public int Id { get; set; }
        public string Text { get; set; }
    }
}