// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScorpionBusterBackEnd.Models
{
    public partial class Map
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public string Background { get; set; }
        public int? PnjId { get; set; }
        public int? MonsterId { get; set; }
    }
}