// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScorpionBusterBackEnd.Models
{
    public partial class Pnj
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Stage { get; set; }
        public string Dialog { get; set; }
        public string Response { get; set; }
        public int? ItemId { get; set; }
        public int? MonsterId { get; set; }
    }
}