// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ScorpionBusterBackEnd.Models;

namespace ScorpionBusterBackEnd.Data
{
    public partial class Scorpionbuster2Context : DbContext
    {
        public Scorpionbuster2Context()
        {
        }

        public Scorpionbuster2Context(DbContextOptions<Scorpionbuster2Context> options)
            : base(options)
        {
        }

        public virtual DbSet<AvailableCharacter> AvailableCharacters { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AvailableCharacter>(entity =>
            {
                entity.ToTable("AvailableCharacter");

                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("id");

                entity.Property(e => e.NomDuPersonnage)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("nomDuPersonnage");

                entity.Property(e => e.ProfilePicUrl)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("profilePicUrl");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}